import { baiJamjuree } from "@/lib/fonts";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "TechGet Ultra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${baiJamjuree.variable}`}>
      <body
        style={{
          fontFamily: "var(--font-bai-jamjuree), sans-serif",
        }}
      >
        <header>
          <Navbar />
        </header>
        <main className="min-h-screen">{children}</main>
        <footer>Footer</footer>
        <Toaster />
      </body>
    </html>
  );
}